### ISSUE TITLE
Remove unnecessary layers in Dockerfile

### ISSUE THREAD

**Issue by mikz** [wernight/docker-plex-media-server#1]
You can take some inspiration in https://github.com/mikz/docker-plex/blob/master/Dockerfile
It is significantly simpler and works like a charm.

For example your getting a deb stores it in a layer, as the remove is in another RUN command. 
So client will have to download it anyway.

**Comment by wernight** [comment]
Thanks, I didn't know each `RUN` incurred another download (no matter how small).
