### ISSUE TITLE
Plex media server 0.9.14.6.1620 build fails

### ISSUE THREAD

**Issue by lanrat** [wernight/docker-plex-media-server#12]
The latest version of PMS does not build
https://hub.docker.com/r/wernight/plex-media-server/builds/bjzedrpgdssnphmnw4tudwk/

**Comment by JigSawFr** [comment]
Same for "autoupdate" branch.
Plex Server down until issue solved. (Unable to download deb)

**Comment by wernight** [comment]
It builds successfully locally so I'm looking at retrying on Docker Hub. At least the previous version is still there until its fixed.

**Comment by wernight** [comment]
Build successful. Also added more granular versioning: `0`, `0.9`, `0.9.14`, `0.9.14.6`.
