### ISSUE TITLE
Improve auto-update error

### ISSUE THREAD

**Issue by wernight** [wernight/docker-plex-media-server#14]
If an error occurs during auto-update retrieval or install of Plex, show a clearly visible message inviting to do a `docker pull wernight/plex-media-server:autoupdate` or `docker-compose pull`.

**Comment by JigSawFr** [comment]
Not possible to do a fallback system ? (to latest public or known plex pass)

**Comment by wernight** [comment]
Good point.

Could wait for input if stdin is open or show a message for something like 30 sec if stdin is closed, and after skip the update part.

However if the user never installed it, it'd fail which I think is okay. The alternative would increase image size and some users may think it autoupdates when it fails due to their network or something.

**Comment by JigSawFr** [comment]
Or it could be great to force a link by an ENV var at run.
For example, if it's crashing as actually, i can go to plex, copy link and force it in my run command, so container will be usable with last plex pass version. And we can wait for an updated image :)

**Comment by wernight** [comment]
Through environment sound hacky and edge case; like for people who really really cannot for to get latest version and have some decent system/programming knowledge, like you. ;)

**Comment by JigSawFr** [comment]
It will be invisible for end user, but available for us by putting 

```
-e PLEX_DL='https://downloads.plex.tv/plex-media-server/0.9.15.0.1621-344f193/plexmediaserver_0.9.15.0.1621-344f193_amd64.deb'
```

:)

**Comment by wernight** [comment]
Feel free to submit in PR. With the two new commits it should be pretty solid.

**Comment by wernight** [comment]
If you do, I'd recommend using explicit names like `PLEX_FORCE_DOWNLOAD_URL` and/or `PLEX_SKIP_UPDATE`.

**Comment by wernight** [comment]
Outside of those it should also show a clear error if username/password are wrong, see #13.

So summary:
- Invite to do `docker pull` (DONE)
- Wrong password message (TODO)
- `PLEX_FORCE_DOWNLOAD_URL` and `PLEX_SKIP_UPDATE` (TODO)
