### ISSUE TITLE
read.me info on docker comparison

### ISSUE THREAD

**Issue by aptalca** [wernight/docker-plex-media-server#18]
Just a heads up, both the linuxserver and the needo versions support plexpass and they have for a while

**Comment by JigSawFr** [comment]
@aptalca the main difference is that linuxserver depends on an API call to their service to get latest plexpass build or public, and here, latest build is directly scrapped from Plex website :)

**Comment by wernight** [comment]
@aptalca Thanks for the update, I've updated the README according.
