### ISSUE TITLE
Troubleshooting: "You do not have permission to access this server"

### ISSUE THREAD

**Issue by bluepuma77** [wernight/docker-plex-media-server#2]
I am having an issue using my own Plex server, even though I am logged in.
1. I did a fresh `sudo docker pull wernight/plex-media-server`
2. I started up Docker with `wernight/plex-media-server` on my hosted linux server
3. I registered and confirmed a new (free) account on plex.tv
4. I logged in on my server with the new Plex account
5. But then I got the message "_You do not have permission to access this server_"

Directories are writable, the container created `/plex-config/Plex Media Server`, I used this command:
`sudo docker run -d --restart=always --user www-data --name plex -v /data/download/plex-config:/config -v /data/download:/media -p 32400:32400 wernight/plex-media-server`

The Preferences.xml file was automatically created and has this content `<Preferences MachineIdentifier="1**f" ProcessedMachineIdentifier="1**f" AnonymousMachineIdentifier="1**f" MetricsEpoch="1" GracenoteUser="1**f"/>`

Do I need to configure something else? Does this only work with Plex premium pass?

![plex-permissions](https://cloud.githubusercontent.com/assets/5221187/9283236/5b39a178-42d2-11e5-8194-dc760a068d6b.png)

**Comment by bluepuma77** [comment]
This is how the login screen looks like, it also enables sign-up with plex.tv.
![plex-login](https://cloud.githubusercontent.com/assets/5221187/9283590/35db250c-42d5-11e5-8cfa-e40dd3befea2.png)

**Comment by bluepuma77** [comment]
Plex version is Version 2.4.16

**Comment by bluepuma77** [comment]
Plex version is 2.4.16

**Comment by bluepuma77** [comment]
Here is the solution, thanks to Plex forum (and docs), maybe you want to add this to "_Troubleshooting_".

`On a Different Network`
`If you're on a different network than the Server computer, you'll first need to set up a SSH tunnel so that you can access things as if they were local. This is only necessary for the initial setup.`

Command line for local SSH tunnel to server: `ssh -L 32400:localhost:32400 -N user@remote.server`

Then connect with your browser to `localhost:32400/web` and login with your plex.tv user.

From now on you can connect directly to your remote server with your plex.tv user.

**Comment by bluepuma77** [comment]
To be able to connect with phone and tablet apps to the Docker container, you need to go to `Settings -> Server -> Remote Access` in the web app and activate "Manually specify port", even if you use the default port 32400.

**Comment by wernight** [comment]
It's already in the FAQ of this docket under troubleshooting I believe.

**Comment by wernight** [comment]
If you think the README should be clarified, please suggest improvements.
