### ISSUE TITLE
Official download link (plexpass)

### ISSUE THREAD

**Issue by jkaberg** [wernight/docker-plex-media-server#20]
Don't know if you want to rework how its done, but this link returns latest plexpass release

> https://plex.tv/downloads/latest/1?channel=8&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token= -- x-plex-token --

I guess removing &X-Plex-Token=.. will return none plexpass :santa: 

[Find PLEX Token](https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token)

**Comment by wernight** [comment]
Nice
I'll probably update as it seems more stable.

**Comment by JigSawFr** [comment]
Very nice, could be great to use this link !

**Comment by wernight** [comment]
Done in https://github.com/wernight/docker-plex-media-server/commit/3c2cc740c75bf17e0737fdbf520423def3a79aba
