### ISSUE TITLE
upgrade to autoupdate

### ISSUE THREAD

**Issue by laouache** [wernight/docker-plex-media-server#22]
Hello,

I just notice that with your tag autoupdate, you download always the plex...deb without testing the installed version in the docker. If I'm right, I suggest you to integrate this script in your docker to test this thing : https://github.com/mrworf/plexupdate/blob/master/plexupdate.sh
With this option  -p -d -a

What do you think about this ?

**Comment by wernight** [comment]
It's indeed installing it each time without version check at the moment.

However it's doing it in a better way than plexupdate.sh by using x-plex-token or a browser instead of curl.
