### ISSUE TITLE
Unable to use my own uid with autoupdate

### ISSUE THREAD

**Issue by sdier** [wernight/docker-plex-media-server#26]
With my own uid set (and even after changing the name from plex to another name) I keep getting permission denied errors from the curl of the plex deb. :(  I dropped --user and set the uid in passwd to the same as your package and it worked. (after re-chowning everything)  Are you able to reproduce?

**Comment by wernight** [comment]
Check the readme, it's not possible as root is required to install
packages. After that it should run as a normal user. You can use the non
auto update version if you want to initially run as non root.

**Comment by sdier** [comment]
Whoops, sorry about that, missed that in the readme.
