### ISSUE TITLE
Sqlite database locked on first boot, docker windows beta

### ISSUE THREAD

**Issue by cat5inthecradle** [wernight/docker-plex-media-server#27]
To start, I'm using the new Docker Windows Beta, perhaps that is related.

On boot, the site is inaccessible, and the logs being written to my config volume look like this, over and over.

`May 29, 2016 00:55:20 [0x7fc4f33fe700] INFO - Plex Media Server v0.9.16.4.1911-ee6e505 - ubuntu PC x86_64 - build: linux-ubuntu-x86_64 ubuntu
May 29, 2016 00:55:20 [0x7fc4f33fe700] INFO - Linux version: 4.4.11-moby (#1 SMP Mon May 23 20:46:49 UTC 2016)
May 29, 2016 00:55:20 [0x7fc4f33fe700] INFO - Processor Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
May 29, 2016 00:55:20 [0x7fc4ff61a800] DEBUG - BPQ: [Idle] -> [Starting]
May 29, 2016 00:55:20 [0x7fc4ff61a800] DEBUG - Opening 20 database sessions to library, SQLite 3.8.9, threadsafe=1
May 29, 2016 00:55:35 [0x7fc4ff61a800] ERROR - SQLITE3:0x10, 5, statement aborts at 2: [PRAGMA journal_mode=WAL] 
May 29, 2016 00:55:35 [0x7fc4ff61a800] ERROR - Database corruption: sqlite3_statement_backend::loadOne: database is locked
May 29, 2016 00:55:35 [0x7fc4ff61a800] ERROR - Error: Unable to set up server: sqlite3_statement_backend::loadOne: database is locked
`

I've double checked permissions. Docker is using my administrator credentials for the volumes, and I gave "Everyone" full access to the config path. The container is able to successfully write to the config path.

The SQLite db is internal though, right? Not in /config or /media. So it seems like an internal permission issue. Thoughts?

Started with:

`docker run -d --restart=always --name plex --env-file ./env.list -v D:/docker/plex/config:/config -v M:/Media:/media -p 32400:32400 wernight/plex-media-server`

env file just contains my plex credentials.

**Comment by wernight** [comment]
ACL must be the one of Linux and not Docker. Docker runs as "admin" but
things inside the container should run as limited user in this image
(except the upgrade of the autoupdate tag).

In theory it should work just the same as that's what Docker does but
that's beta so might be an issue with it.

**Comment by cat5inthecradle** [comment]
thanks for the response. I tried one of the other popular plex docker implementations, and I eventually ended up at a similar issue. I'll blame the Beta for this until I learn more about this stuff.

**Comment by salarali** [comment]
I had the same error when I mapped the config folder onto a Windows folder. I removed that and the server started working.

**Comment by wernight** [comment]
On Linux we have user:group, and Windows has more complex rules but completely different and in a almost hidden UI (used to be under Permissions). May be running as another user or giving other permissions works.

Another possibly better alternative is to use docker volumes like https://docs.docker.com/engine/tutorials/dockervolumes/ (I prefer the docker-compose way but should be same).
