### ISSUE TITLE
Transcode

### ISSUE THREAD

**Issue by marcgiovannoni** [wernight/docker-plex-media-server#30]
Hi,

Would it be possible to add a separate `/transcode` volume instead of being defaulted to the `/config` folder.

Transcode requires lots of space, as a user you might want to use a special partition/volume to handle the transcode and use a more usual location for the appdata folder `/config`

**Comment by lanrat** [comment]
I totally agree! This makes my automated backups of the config volume unnessessarally large.

While we are at it can `/config/Plex Media Server/Cache` and `/config/Plex Media Server/Metadata` also me moved a new volume?

**Comment by wernight** [comment]
You can change your plex config. I'd keep the number of mounts to a minimum by default. You can also `ln -s` on the host.

**Comment by marcgiovannoni** [comment]
I will close the issue then. Thanks
