### ISSUE TITLE
Specify .deb file for latest branch, similar to autoupdate branch.

### ISSUE THREAD

**Issue by brannon-bowden** [wernight/docker-plex-media-server#36]
I love your docker image, but occasionally want to update when you haven't yet. It would be nice to have this feature that the autoupdate branch has.

**Comment by wernight** [comment]
Building from master will retrieve the latest version. I changed to rebuild more frequently which should keep it more up to date.

This branch runs as non-root right from the start, so it cannot update Plex (that would defeat most of the non-root usage).
