### ISSUE TITLE
curl issue?

### ISSUE THREAD

**Issue by Snaver** [wernight/docker-plex-media-server#44]
**Host OS:** Linux (Ubuntu 16.04.3)
**Tag/Version:** latest

**Steps:**

 1. sudo docker run --rm -it wernight/plex-media-server retrieve-plex-token

**Expected:**

token..

**Actual:**

> `Retrieving a X-Plex-Token using Plex login/password...
> curl: /usr/lib/plexmediaserver/libcurl.so.4: no version information available (required by curl)
> curl: (48) An unknown option was passed in to libcurl

I think there's a large problem here, as looking at the Docker logs when I attempt to pass `-e X_PLEX_TOKEN='<my_x_plex_token>'` I see the same errors.

**Comment by wernight** [comment]
Delete the container should work. I thought it got updated and stopped using curl as Plex installs its own.

**Comment by Snaver** [comment]
Hmm that didn't work either :(

```
user@ubuntu-xenial:~$ sudo docker run --rm -it wernight/plex-media-server retrieve-plex-token
Unable to find image 'wernight/plex-media-server:latest' locally
latest: Pulling from wernight/plex-media-server
e7bb522d92ff: Pull complete
269f3fb49f70: Pull complete
1975bb3ddda2: Pull complete
f2497df92dee: Pull complete
Digest: sha256:7d12babe0c9128abc5db624ce174a29faf0d96454a73f2722d6fa09d632b3f37
Status: Downloaded newer image for wernight/plex-media-server:latest
8192
Your Plex login (e-mail or username): XXXX
Your Plex password: XXX
Retrieving a X-Plex-Token using Plex login/password...
curl: /usr/lib/plexmediaserver/libcurl.so.4: no version information available (required by curl)
curl: (48) An unknown option was passed in to libcurl
user@ubuntu-xenial:~$
```

Software versions:

> server@ubuntu-xenial:~$ docker -v
> Docker version 17.12.0-ce, build c97c6d6

**Comment by carlba** [comment]
What's happening with this?

**Comment by marklagace** [comment]
I'm having the same issue as the original poster.

> docker run --rm -it wernight/plex-media-server retrieve-plex-token
> Unable to find image 'wernight/plex-media-server:latest' locally
> latest: Pulling from wernight/plex-media-server
> 6ae821421a7d: Pull complete 
> 8025ccf31870: Pull complete 
> 991570ce7417: Pull complete 
> 65862e8a3946: Pull complete 
> Digest: sha256:86b711ed01962f81f03070c999074f67e67653d1f510c2369cc66442a3390df9
> Status: Downloaded newer image for wernight/plex-media-server:latest
> 8192
> Your Plex login (e-mail or username): XXXX
> Your Plex password: XXXX
> Retrieving a X-Plex-Token using Plex login/password...
> curl: /usr/lib/plexmediaserver/libcurl.so.4: no version information available (required by curl)
> curl: (48) An unknown option was passed in to libcurl

Host: Gentoo Linux
Docker version 18.06.1-ce, build e68fc7a

EDIT: If I specify version 1.14.1 it works.

**Comment by lukasa1993** [comment]
still happening

**Comment by wernight** [comment]
`docker run --rm -it wernight/plex-media-server retrieve-plex-token` should automatically pull from Docker Hub. You could try manually doing `docker pull wernight/plex-media-server` but that shouldn't be necessary. I think there is some issue with your local docker install.

Regarding the bug with curl, I could repro now, so I'll fix it.

**Comment by wernight** [comment]
Should be fixed now.
