### ISSUE TITLE
1.15.0.647 - Fails to launch - Can’t find libva.so.2

### ISSUE THREAD

**Issue by voidstar-x** [wernight/docker-plex-media-server#46]
Host OS: Ubuntu Linux
Tag/Version: autoupdate

From the official Plex team:

"In an attempt to resolve all the possible variations out there:

Plex Official Docker = https://github.com/plexinc/pms-docker 3 (fix commit https://github.com/plexinc/pms-docker/commit/0e81f12e599d83db99b7d2bd1c94b1a29088b2e7 9)
plexinc/pms-docker

Linuxserver.io 1 Docker = https://github.com/linuxserver/docker-plex 2 (fix commit https://github.com/linuxserver/docker-plex/commit/202321e3b93b3875673c894d070a9f0057d3c584)
linuxserver/docker-plex

If users are running either of those, they need to pull the latest version of the container.

If they are using another Docker PMS container, they need to reach out to the maintainer and have them fix the LD_LIBRARY_PATH"

https://forums.plex.tv/t/1-15-0-647-fails-to-launch-cant-find-libva-so-2/372520/21

**Comment by wernight** [comment]
Looks like they move the libraries directory.
