### ISSUE TITLE
Unable to create a new plex-pass container

### ISSUE THREAD

**Issue by iXo** [wernight/docker-plex-media-server#8]
I am using this command to check the good start of a new container : `docker run --name=plex -v /shyrka/docker/plex/config:/config -v /Volumes/music:/media --net=host -p 32400:32400 -e PLEXPASS_LOGIN='snip' -e PLEXPASS_PASSWORD='snip' wernight/plex-media-server:autoupdate`

And it seems there is a problem during the generation of the deb url ?

```
8192
+ /retrieve_plex_download_url.py
Retrieving the latest Plex release for PlexPass users...
Traceback (most recent call last):
  File "/retrieve_plex_download_url.py", line 51, in <module>
    print(retrieve_latest_download_url(login, password))
  File "/retrieve_plex_download_url.py", line 40, in retrieve_latest_download_url
    assert len(links) == 1
AssertionError
+ curl -L -o plexmediaserver.deb
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

I am new to docker, so maybe I miss something.

**Comment by iXo** [comment]
Ok, I tried to find the problem, and found that this part of the script `curl -Ls https://plex.tv/downloads | grep -o '^"'"'"'*amd64.deb' | grep -v binaries` doesn't works, and return empty strings.

In a shell, I have tried using this command instead : `curl -Ls https://plex.tv/downloads | grep -o 'http.*amd64.deb' | grep -v binaries` and it return a full valid url : `https://downloads.plex.tv/plex-media-server/0.9.14.6.1620-e0b7243/plexmediaserver_0.9.14.6.1620-e0b7243_amd64.deb`

The problem, is I am not able to udpate the script as I don't know how to modifiy it.

**Comment by iXo** [comment]
Found the problem : the links text for plex pass have changed, `64-bit` is now `64 bits` here is the change :

```
links = [link for link in browser.links() if '.deb' in link.url and (link.text == '64-bit' or link.text == '64 bits')]
```

**Comment by wernight** [comment]
Thanks for the notification, I'll update once I'm on a stable network.
