### ISSUE TITLE
Real server range for settings in README

### ISSUE THREAD

**Issue by JigSawFr** [wernight/docker-plex-media-server#9]
Hi,
I suggest you to add some instructions to README
As to view Plex Settings, you need to add IP range of docker (take a look with a netconfig),
Most of the time it's 172.17.0.1/255.255.0.0
So, adding **allowedNetworks="172.17.0.1/255.255.0.0"** works fine !
No need to change networking of container or add other range ;)

**Comment by wernight** [comment]
There is already a section like that under [Troubleshooting](https://github.com/wernight/docker-plex-media-server#troubleshooting); may be could detail it a bit.

A better option may be to include both `192.168.0.1/255.255.0.0, 172.17.0.1/255.255.0.0` by default if Plex supports having both ranges.

**Comment by JigSawFr** [comment]
@wernight yes, Plex support multiple range separated by a comma.

**Comment by wernight** [comment]
I wonder if this is still something desired. It could open security bugs like IP spoofing in some cases. The alternative of `--net=host` works, and the other improved alternative is to provide a username/password or token and those should now work also very soon.
